// SPDX-License-Identifier: MIT
//
// Copyright 2025 dgz
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the “Software”), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "compiler.h"
#include "util.h"

#define HAL_IOMUX ((struct hal_iomux_regs *const)(0x40428000))

// clang-format off

#define HAL_IOMUX_PIN_DIGITAL_FUNC_GPIO	(BIT_1)

#define HAL_IOMUX_PIN_PA0_DIGITAL_FUNC_BEEP		(BIT_2)
#define HAL_IOMUX_PIN_PA0_DIGITAL_FUNC_I2C0_SDA		(BIT_3)
#define HAL_IOMUX_PIN_PA0_DIGITAL_FUNC_TIMG8_C0		(BIT_4)
#define HAL_IOMUX_PIN_PA0_DIGITAL_FUNC_SPI0_CS1		(BIT_5)
#define HAL_IOMUX_PIN_PA0_DIGITAL_FUNC_FCC_IN		(BIT_6)
#define HAL_IOMUX_PIN_PA0_DIGITAL_FUNC_TIMA_FAL1	(BIT_7)

#define HAL_IOMUX_PIN_PA1_DIGITAL_FUNC_I2C0_SCL		(BIT_2)
#define HAL_IOMUX_PIN_PA1_DIGITAL_FUNC_TIM8_C0		(BIT_3)
#define HAL_IOMUX_PIN_PA1_DIGITAL_FUNC_HFCLK_IN		(BIT_4)
#define HAL_IOMUX_PIN_PA1_DIGITAL_FUNC_TIMA0_C1		(BIT_5)

#define HAL_IOMUX_PIN_PA2_DIGITAL_FUNC_TIMG8_C1		(BIT_2)
#define HAL_IOMUX_PIN_PA2_DIGITAL_FUNC_SPI0_CS0		(BIT_3)
#define HAL_IOMUX_PIN_PA2_DIGITAL_FUNC_TIMA0_C0		(BIT_4)
#define HAL_IOMUX_PIN_PA2_DIGITAL_FUNC_TIMG8_IDX	(BIT_5)

#define HAL_IOMUX_PIN_PA4_DIGITAL_FUNC_TIMA0_C0N	(BIT_2)
#define HAL_IOMUX_PIN_PA4_DIGITAL_FUNC_SPI0_POCI	(BIT_3)
#define HAL_IOMUX_PIN_PA4_DIGITAL_FUNC_LFCLK_IN		(BIT_4)
#define HAL_IOMUX_PIN_PA4_DIGITAL_FUNC_HFCLK_IN		(BIT_5)
#define HAL_IOMUX_PIN_PA4_DIGITAL_FUNC_TIMA0_C1N	(BIT_6)

#define HAL_IOMUX_PIN_PA6_DIGITAL_FUNC_TIMG14__C1	(BIT_2)
#define HAL_IOMUX_PIN_PA6_DIGITAL_FUNC_SPI0_SCK		(BIT_3)
#define HAL_IOMUX_PIN_PA6_DIGITAL_FUNC_TIMA0_C1		(BIT_4)
#define HAL_IOMUX_PIN_PA6_DIGITAL_FUNC_TIMG14_C2	(BIT_5)
#define HAL_IOMUX_PIN_PA6_DIGITAL_FUNC_SPI0_CS0		(BIT_6)
#define HAL_IOMUX_PIN_PA6_DIGITAL_FUNC_TIMA_FAL0	(BIT_7)

#define HAL_IOMUX_PIN_PA11_DIGITAL_FUNC_SPI0_SCK	(BIT_2)
#define HAL_IOMUX_PIN_PA11_DIGITAL_FUNC_I2C0_SCL	(BIT_3)
#define HAL_IOMUX_PIN_PA11_DIGITAL_FUNC_TIMA_FAL0	(BIT_4)

#define HAL_IOMUX_PIN_PA16_DIGITAL_FUNC_TIMA0_C1N	(BIT_2)
#define HAL_IOMUX_PIN_PA16_DIGITAL_FUNC_SPI0_POCI	(BIT_3)
#define HAL_IOMUX_PIN_PA16_DIGITAL_FUNC_TIMG14_C0	(BIT_4)
#define HAL_IOMUX_PIN_PA16_DIGITAL_FUNC_FCC_IN		(BIT_5)

#define HAL_IOMUX_PIN_PA17_DIGITAL_FUNC_UART0_TX	(BIT_2)
#define HAL_IOMUX_PIN_PA17_DIGITAL_FUNC_TIMA0_C0N	(BIT_3)
#define HAL_IOMUX_PIN_PA17_DIGITAL_FUNC_SPI0_SCK	(BIT_4)
#define HAL_IOMUX_PIN_PA17_DIGITAL_FUNC_TIMA0_C2	(BIT_5)
#define HAL_IOMUX_PIN_PA17_DIGITAL_FUNC_SPI0_CS1	(BIT_6)
#define HAL_IOMUX_PIN_PA17_DIGITAL_FUNC_TIMA0_C3	(BIT_7)

#define HAL_IOMUX_PIN_PA18_DIGITAL_FUNC_UART0_RX	(BIT_2)
#define HAL_IOMUX_PIN_PA18_DIGITAL_FUNC_SPI0_PICO	(BIT_3)
#define HAL_IOMUX_PIN_PA18_DIGITAL_FUNC_TIMA0_C1N	(BIT_4)
#define HAL_IOMUX_PIN_PA18_DIGITAL_FUNC_CLK_OUT		(BIT_5)
#define HAL_IOMUX_PIN_PA18_DIGITAL_FUNC_TIMA0_C3	(BIT_6)
#define HAL_IOMUX_PIN_PA18_DIGITAL_FUNC_TIMA0_C3N	(BIT_7)

#define HAL_IOMUX_PIN_PA19_DIGITAL_FUNC_SWDIO		(BIT_2)
#define HAL_IOMUX_PIN_PA19_DIGITAL_FUNC_SPI0_SCK	(BIT_3)
#define HAL_IOMUX_PIN_PA19_DIGITAL_FUNC_SPI0_POCI	(BIT_4)
#define HAL_IOMUX_PIN_PA19_DIGITAL_FUNC_TIMA0_C2	(BIT_5)
#define HAL_IOMUX_PIN_PA19_DIGITAL_FUNC_TIMG14_C0	(BIT_6)
#define HAL_IOMUX_PIN_PA19_DIGITAL_FUNC_UART0_CTS	(BIT_7)

#define HAL_IOMUX_PIN_PA20_DIGITAL_FUNC_SWCLK		(BIT_2)
#define HAL_IOMUX_PIN_PA20_DIGITAL_FUNC_TIMA_FAL1	(BIT_3)
#define HAL_IOMUX_PIN_PA20_DIGITAL_FUNC_SPI0_PICO	(BIT_4)
#define HAL_IOMUX_PIN_PA20_DIGITAL_FUNC_TIMA0_C2N	(BIT_5)
#define HAL_IOMUX_PIN_PA20_DIGITAL_FUNC_TIMA0_C0	(BIT_6)
#define HAL_IOMUX_PIN_PA20_DIGITAL_FUNC_UART0_RTS	(BIT_7)

#define HAL_IOMUX_PIN_PA22_DIGITAL_FUNC_UART0_RX	(BIT_2)
#define HAL_IOMUX_PIN_PA22_DIGITAL_FUNC_SPI0_POCI	(BIT_3)
#define HAL_IOMUX_PIN_PA22_DIGITAL_FUNC_UART0_RTS	(BIT_4)
#define HAL_IOMUX_PIN_PA22_DIGITAL_FUNC_CLK_OUT		(BIT_5)
#define HAL_IOMUX_PIN_PA22_DIGITAL_FUNC_TIMA0_C1	(BIT_6)

#define HAL_IOMUX_PIN_PA23_DIGITAL_FUNC_UART0_TX	(BIT_2)
#define HAL_IOMUX_PIN_PA23_DIGITAL_FUNC_SPI0_CS3	(BIT_3)
#define HAL_IOMUX_PIN_PA23_DIGITAL_FUNC_TIMG14_C0	(BIT_4)
#define HAL_IOMUX_PIN_PA23_DIGITAL_FUNC_UART0_CTS	(BIT_5)
#define HAL_IOMUX_PIN_PA23_DIGITAL_FUNC_TIMA0_C3	(BIT_6)
#define HAL_IOMUX_PIN_PA23_DIGITAL_FUNC_TIMG14_C1	(BIT_7)

#define HAL_IOMUX_PIN_PA24_DIGITAL_FUNC_SPI0_CS2	(BIT_2)
#define HAL_IOMUX_PIN_PA24_DIGITAL_FUNC_TIMG14_C1	(BIT_3)
#define HAL_IOMUX_PIN_PA24_DIGITAL_FUNC_UART0_RTS	(BIT_4)
#define HAL_IOMUX_PIN_PA24_DIGITAL_FUNC_TIMG14_C2	(BIT_5)
#define HAL_IOMUX_PIN_PA24_DIGITAL_FUNC_TIMA0_C3N	(BIT_6)
#define HAL_IOMUX_PIN_PA24_DIGITAL_FUNC_UART0_RX	(BIT_7)

#define HAL_IOMUX_PIN_PA25_DIGITAL_FUNC_TIMG14_C3	(BIT_2)
#define HAL_IOMUX_PIN_PA25_DIGITAL_FUNC_UART0_TX	(BIT_3)
#define HAL_IOMUX_PIN_PA25_DIGITAL_FUNC_SPI0_PICO	(BIT_4)
#define HAL_IOMUX_PIN_PA25_DIGITAL_FUNC_TIMG14_C1	(BIT_5)
#define HAL_IOMUX_PIN_PA25_DIGITAL_FUNC_TIMA_FAL2	(BIT_6)

#define HAL_IOMUX_PIN_PA26_DIGITAL_FUNC_TIMG8_C0	(BIT_2)
#define HAL_IOMUX_PIN_PA26_DIGITAL_FUNC_UART0_RX	(BIT_3)
#define HAL_IOMUX_PIN_PA26_DIGITAL_FUNC_SPI0_POCI	(BIT_4)
#define HAL_IOMUX_PIN_PA26_DIGITAL_FUNC_BEEP		(BIT_5)
#define HAL_IOMUX_PIN_PA26_DIGITAL_FUNC_TIMG14_C0	(BIT_6)
#define HAL_IOMUX_PIN_PA26_DIGITAL_FUNC_TIMA_FAL0	(BIT_7)

#define HAL_IOMUX_PIN_PA27_DIGITAL_FUNC_TIMG8_C1	(BIT_2)
#define HAL_IOMUX_PIN_PA27_DIGITAL_FUNC_SPI0_CS3	(BIT_3)
#define HAL_IOMUX_PIN_PA27_DIGITAL_FUNC_TIMA0_C0N	(BIT_4)
#define HAL_IOMUX_PIN_PA27_DIGITAL_FUNC_UART0_TX	(BIT_5)
#define HAL_IOMUX_PIN_PA27_DIGITAL_FUNC_SPI0_POCI	(BIT_6)
#define HAL_IOMUX_PIN_PA27_DIGITAL_FUNC_TIMA_FAL2	(BIT_7)

#define HAL_IOMUX_PIN_PA28_DIGITAL_FUNC_TIMA0_C0	(BIT_2)
#define HAL_IOMUX_PIN_PA28_DIGITAL_FUNC_UART0_RX	(BIT_3)
#define HAL_IOMUX_PIN_PA28_DIGITAL_FUNC_TIMG8_IDX	(BIT_4)

// clang-format on

enum hal_iomux_pincm {
	// clang-format off

	HAL_IOMUX_PINCM_PA0	= 0,
	HAL_IOMUX_PINCM_PA1	= 1,
	HAL_IOMUX_PINCM_PA2	= 2,
	HAL_IOMUX_PINCM_PA4	= 4,
	HAL_IOMUX_PINCM_PA6	= 6,
	HAL_IOMUX_PINCM_PA11	= 11,
	HAL_IOMUX_PINCM_PA16	= 16,
	HAL_IOMUX_PINCM_PA17	= 17,
	HAL_IOMUX_PINCM_PA18	= 18,
	HAL_IOMUX_PINCM_PA19	= 19,
	HAL_IOMUX_PINCM_PA20	= 20,
	HAL_IOMUX_PINCM_PA22	= 22,
	HAL_IOMUX_PINCM_PA23	= 23,
	HAL_IOMUX_PINCM_PA24	= 24,
	HAL_IOMUX_PINCM_PA25	= 25,
	HAL_IOMUX_PINCM_PA26	= 26,
	HAL_IOMUX_PINCM_PA27	= 27,
	HAL_IOMUX_PINCM_PA28	= 28,
	HAL_IOMUX_PINCM_NUM_MAX

	// clang-format on
};

struct hal_iomux_regs {
	const uint32_t pad;

	volatile uint32_t PINCM[HAL_IOMUX_PINCM_NUM_MAX];
};

enum hal_iomux_resistor_type {
	/** No programmable resistor will be used. */
	HAL_IOMUX_RESISTOR_TYPE_NONE = 0,

	/** Programmable pull-up resistor will be used. */
	HAL_IOMUX_RESISTOR_TYPE_PULL_UP = 1,

	/** Programmable pull-down resistor will be used. */
	HAL_IOMUX_RESISTOR_TYPE_PULL_DOWN = 2
};

STATIC_ASSERT_OFFSET(struct hal_iomux_regs, PINCM, 0x4);

void hal_iomux_set_pin_inv(enum hal_iomux_pincm pincm, bool inv);

void hal_iomux_set_pin_hysteresis(enum hal_iomux_pincm pincm, bool hysteresis);

void hal_iomux_set_pin_resistor(enum hal_iomux_pincm pincm,
				enum hal_iomux_resistor_type resistor_type);

void hal_iomux_set_pin_func(enum hal_iomux_pincm pincm, uint8_t func,
			    bool input_enabled);

extern const uint32_t hal_iomux_valid_pincm_mask;
